book_system/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include('web.urls')),
]


urlpatterns += staticfiles_urlpatterns()

web/urls.py
from django.conf.urls import url
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles

urlpatterns = [
    url(r'^favorites', views.favorites),
    url(r'^login', views.login),
    # url(r'^welcome',views.welcome ),
    url(r'^register', views.register),
    url(r'^home', views.home),
    url(r'^PCenter', views.PCenter),
    url(r'^upload',views.upload),
    url(r'^selling',views.selling),
    url(r'^book/$', views.book),
    url(r'^book_col/$', views.book_col),
    url(r'^book_cal/$', views.book_cal),
    url(r'^own_book/$', views.own_book),
    url(r'^book_result', views.book_result),
    url(r'^buyer_center/$', views.buyer_center),
    url(r'^seller_center', views.seller_center),
    url(r'^comment/$', views.comment),
    url(r'^tobuyer_comment/$', views.tobuyer_comment),
    url(r'^others_center/$', views.others_center),
    url(r'^favorites', views.favorites),
    url(r'^success_return/$', views.success_return),
]

urlpatterns += staticfiles_urlpatterns()

web/models.py
# encoding:utf-8
from __future__ import unicode_literals
from django.db import models

from django import utils
# Create your models here.
class User(models.Model):
    college=models.CharField(blank=True,null=True,max_length=32)
    major=models.CharField(blank=True,null=True,max_length=32)
    in_year=models.IntegerField(blank=True,null=True,default=0)
    campus=models.CharField(blank=True,null=True,max_length=16)

    nickname = models.CharField(blank=True,null=True,max_length=20,)
    contact=models.CharField(blank=True,null=True,max_length=40,default='None')
    student_id = models.CharField(blank=True, null=True, max_length=64)
    username = models.CharField(max_length=20,primary_key=True )#主码
    password = models.CharField(max_length=20, )
    image = models.ImageField(blank=True, null=True,upload_to='')
    states = (
        (0, "using"),
        (1, "closed"),
    )
    state = models.IntegerField(blank=True, null=True, choices=states,default=0)

    num=models.IntegerField(default=0)
    description=models.CharField(blank=True, null=True,max_length=200)

class Book(models.Model):
    ways = (
        (0, 'cancle'),
        (1, u'面交'),
        (2, u'快递'),
        (3, u'面交或快递'),
    )
    bookname = models.CharField(blank=True,null=True,max_length=20,)
    author=models.CharField(blank=True,null=True,max_length=20,)
    publisher=models.CharField(blank=True,null=True,max_length=20,)
    price = models.FloatField(blank=True,null=True,max_length=24)
    description=models.TextField(blank=True,null=True,)
    way=models.IntegerField(blank=True,null=True,choices=ways)
    picture=models.ImageField(blank=True,null=True,upload_to='',default='logo.png')
    seller= models.ForeignKey(User)
    states = (
        (0, 'on sale'),
        (1, 'sold'),
        (2, 'cancle'),
    )
    state = models.IntegerField(blank=True, null=True,choices=states,default=0)


#class relation(models.Model):
#   seller_name=models.CharField(blank=True,null=True,max_length=20,)
#    buyer_name=models.CharField(blank=True,null=True,max_length=20,)
#    book_id=models.CharField(blank=True,null=True,max_length=20,)
#    date=models.DateField(blank=True,null=True)
#    state=models.IntegerField(blank=True,null=True,default=0)
#    comment=models.CharField(blank=True,null=True,max_length=200,default='None')

class s_b(models.Model):
    user_id = models.CharField(blank=True, null=True, max_length=20, )
    book_id = models.CharField(blank=True, null=True, max_length=20, )
    relation = models.CharField(blank=True, null=True,max_length=10)

class Order(models.Model):
    states = (
        (0, 'buy'),
        (1, 'cancle'),
    )
    seller_name = models.CharField(blank=True, null=True, max_length=20, )
    buyer_name = models.CharField(blank=True, null=True, max_length=20, )
    seller_id = models.CharField(blank=True, null=True, max_length=64, )
    buyer_id = models.CharField(blank=True, null=True, max_length=64, )
    book_id=models.CharField(max_length=20)
    bookname = models.CharField(blank=True, null=True, max_length=20, )
    picture = models.ImageField(blank=True, null=True, upload_to='', default='logo.png')
    price = models.FloatField(blank=True,null=True,max_length=24)
    date=models.DateField(blank=True,null=True,default=utils.timezone.now)

    state=models.IntegerField(blank=True,null=True,default=0,choices=states)

    comment = models.CharField(blank=True, null=True, max_length=200, default='None')
    score=models.IntegerField(blank=True,null=True,default=0)
    anonymous=models.BooleanField(default=False)
    c_time=models.IntegerField(blank=True, null=True )
    tobuyer_comment = models.CharField(blank=True, null=True, max_length=200, default='None')
    tobuyer_score = models.IntegerField(blank=True, null=True, default=0)
    tobuyer_anonymous = models.BooleanField(default=False)
    tobuyer_c_time=models.IntegerField(blank=True, null=True)

    buyer_image = models.ImageField(blank=True, null=True,upload_to='')
    seller_image = models.ImageField(blank=True, null=True,upload_to='')

    ways = (
        (0, 'cancle'),
        (1, u'面交'),
        (2, u'快递'),
        (3, u'面交或快递'),
    )
    way=models.IntegerField(blank=True,null=True,choices=ways)

web/templates/book.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>易书</title>
    <!-- 包含头部信息用于适应不同设备 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 包含 bootstrap 样式表 -->
    <link rel="stylesheet" href="https://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css">
    <link src="/static/css/head.css" rel="stylesheet" type="text/css"/>
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/static/js/script.js"></script>
</head>
<body>
    <div id="white" style="opacity:0.9;"></div>

    <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/web/home">首页</a>
    </div>
    <div>
        <ul class="nav navbar-nav">

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {{ user }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/PCenter">个人中心</a></li>
                    <li><a href="/web/login">退出登录</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    买家中心 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/buyer_center/?b=-1">已买到的宝贝</a></li>
                    <li><a href="/web/favorites">收藏夹</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    卖家中心 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/upload">发布新的二手课本</a></li>
                    <li><a href="/web/selling">已上架的课本</a></li>
                    <li><a href="/web/seller_center">已卖出的课本</a></li>
                </ul>
            </li>

        </ul>
    </div>
    </div>
</nav>


{% for item in book %}
<div class="container" style="text-align:left;margin-top:40px;">
    <div class="row clearfix">
        <div class="col-md-1 column"></div>
        <div class="col-md-3 column">
            <div style="border:#a4a4a4 1.5pt solid;padding:10px;">
                <img id="bid_pic" src="{{ item.picture.url }}" style="width:100%">
            </div>
            <div style="margin-top:15px;"><a href="/web/book_col/?b={{ item.id }}" data-placement="bottom" title="收藏商品"><div id="store" class="glyphicon glyphicon-star-empty star"></div></a>&nbsp;收藏商品</div>
        </div>
        <div class="col-md-6 column">
            <div style="font-size:30px;"><b><span id="bid_title">{{ item.bookname }}</span></b></div>
            <div style="font-size:20px;margin-top:15px;"><span>价&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;格：￥</span><span style="font-size:25px;color:#68493a" id="bid_price">{{ item.price }}</span></div>
            <div style="font-size:20px;">配送方式：{{ item.get_way_display }}</div>
            <div style="margin-top:20px;">作者：{{ item.author }}</div>
            <div>出版社：{{ item.publisher }}</div>
            <div style="margin-top:20px;"><b>商品介绍</b></div>
            <div>{{ item.description }}</div>
            <div style="text-align:right;margin-top:10px;"><button type="button" style="height:50px;width:200px;font-size:25px;" onclick="location.href=if_buy()">立即购买</button></div>
        </div>
        <div class="col-md-2 column" style="text-align:center;">
            <div style="font-size:10px;">卖家：<a href="/web/others_center/?b={{ item.seller_id }}"> <b>{{ item.seller.nickname }}</b></div>
            <img id="gid_pic" src="{{ item.seller.image.url }}" style="width:50%;margin:15px 0;">

        </div>
    </div>
</div>

    <script type="text/javascript">
    function if_buy(){
        var t=confirm("你确定要拍下这件商品吗？")
        if(t==true){
            return "/web/buyer_center/?b={{ item.id }}"
        }
        else {
            return "#"
        }
    }
    </script>
{% endfor %}
</body>
</html>

web/templates/book_cal.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>易书</title>
    <!-- 包含头部信息用于适应不同设备 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 包含 bootstrap 样式表 -->
    <link rel="stylesheet" href="https://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href="/static/css/head.css" rel="stylesheet" type="text/css"/>
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/static/js/script.js"></script>
</head>
<body>
    <div id="white" style="opacity:0.9;"></div>

    <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/web/home">首页</a>
    </div>
    <div>
        <ul class="nav navbar-nav">

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {{ user }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/PCenter">个人中心</a></li>
                    <li><a href="/web/login">退出登录</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    买家中心 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/buyer_center/?b=-1">已买到的宝贝</a></li>
                    <li><a href="/web/favorites">收藏夹</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    卖家中心 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/upload">发布新的二手课本</a></li>
                    <li><a href="/web/selling">已上架的课本</a></li>
                    <li><a href="/web/seller_center">已卖出的课本</a></li>
                </ul>
            </li>

        </ul>
    </div>
    </div>
</nav>


{% for item in book %}
<div class="container" style="text-align:left;margin-top:40px;">
    <div class="row clearfix">
        <div class="col-md-1 column"></div>
        <div class="col-md-3 column">
            <div style="border:#a4a4a4 1.5pt solid;padding:10px;">
                <img id="bid_pic" src="{{ item.picture.url }}" style="width:100%">
            </div>
            <div style="margin-top:15px;"><a href="/web/book_col/?b={{ item.id }}" data-placement="bottom" title="收藏商品"><div id="store" class="glyphicon glyphicon-star-empty star"></div></a>&nbsp;收藏商品</div>
        </div>
        <div class="col-md-6 column">
            <div style="font-size:30px;"><b><span id="bid_title">{{ item.bookname }}</span></b></div>
            <div style="font-size:20px;margin-top:15px;"><span>价&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;格：￥</span><span style="font-size:25px;color:#68493a" id="bid_price">{{ item.price }}</span></div>
            <div style="font-size:20px;">配送方式：{{ item.get_way_display }}</div>
            <div style="margin-top:20px;">作者：{{ item.author }}</div>
            <div>出版社：{{ item.publisher }}</div>
            <div style="margin-top:20px;"><b>商品介绍</b></div>
            <div>{{ item.description }}</div>
            <div style="text-align:right;margin-top:10px;"><button type="button" style="height:50px;width:200px;font-size:25px;" onclick="location.href=if_buy()">立即购买</button></div>
        </div>
        <div class="col-md-2 column" style="text-align:center;">
            <div style="font-size:10px;">卖家：<a href="/web/others_center/?b={{ item.seller_id }}"> <b>{{ item.seller.nickname }}</b></div>
            <img id="gid_pic" src="{{ item.seller.image.url }}" style="width:50%;margin:15px 0;">

        </div>
    </div>
</div>

    <script type="text/javascript">
    function if_buy(){
        var t=confirm("你确定要拍下这件商品吗？")
        if(t==true){
            return "/web/buyer_center/?b={{ item.id }}"
        }
        else {
            return "#"
        }
    }
    </script>
{% endfor %}
</body>
</html>

web/templates/others_center.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>易书</title>
    <!-- 包含头部信息用于适应不同设备 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 包含 bootstrap 样式表 -->
    <link rel="stylesheet" href="https://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href="/static/css/head.css" rel="stylesheet" type="text/css"/>
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div id="white" style="opacity:0.9;"></div>

    <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid"> 
    <div class="navbar-header">
        <a class="navbar-brand" href="/web/home">首页</a>
    </div>
    <div>
        <ul class="nav navbar-nav">

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {{ nick }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/PCenter">个人中心</a></li>
                    <li><a href="/web/login">退出登录</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    买家中心 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/buyer_center/?b=-1">已买到的宝贝</a></li>
                    <li><a href="/web/favorites">收藏夹</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    卖家中心 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/upload">发布新的二手课本</a></li>
                    <li><a href="/web/selling">已上架的课本</a></li>
                    <li><a href="/web/seller_center">已卖出的课本</a></li>
                </ul>
            </li>

        </ul>
    </div>
    </div>
</nav>

<div class="container" style="text-align:left;">
    <div class="row clearfix">
        <div class="col-md-1 column">
            <img src="{{ others.image.url }}" width="72" height="72" class="head">
        </div>
        <div class="col-md-3 column" style="margin-top:10px;">
            <div style="font-size:25px;">{{ others.nickname }}</div>
            <div style="font-size:15px;">华南理工大学{{ others.campus }}</div>
        </div>
    </div>
    <div class="row clearfix" style="margin-top:20px;">
        <div class="col-md-12 column">
            <ul id="myTab" class="nav nav-tabs" style="margin-bottom:20px;">
                <li><a href="#info" data-toggle="tab">个人资料</a></li>
                <li class="active"><a href="#auction_list" data-toggle="tab">发布的商品[{{ book_len }}]</a></li>
                <li><a href="#evaluation" data-toggle="tab">收到的评价[{{len }} ]</a></li>
            </ul>
            <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade" id="info">
                    <p><span><b>学&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;院：</b></span><span>{{ others.college }}</span></p>

                    <p><span><b>专&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;业：</b></span><span>{{ others.major }}</span></p>
                    <p><span><b>年&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;级：</b></span><span>{{ others.in_year }}级</span></p>
                                      <p><span><b>联系方式：</b></span><span>{{ others.contact }}</span></p>
                    <p><span><b>个人简介：</b></span><span>{{ others.description }}</span></p>
                </div>
                <div class="tab-pane fade in active" id="auction_list">
                    <div class="container">
                        <div class="row clearfix" style="margin-bottom:20px;">
                            <div class="col-md-8 column"></div>
                            <div class="col-md-4 column">
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input style="margin-top:12px;margin-left:20px;" name="search" id="search_store_block" onKeyup="getContent(this);" value="搜索TA发布的课本" onfocus="if(this.value=='搜索TA发布的课本'){this.value=''}" onblur="if(this.value==''){this.value='搜索TA发布的课本'}"/>
                                    <input type="submit" class="btn btn-default" style="height:30px;margin-bottom:2px;"value="搜索">
                                </form>
                            </div>
                        </div>
                        <div class="row clearfix">
                            {% for item in book %}
                            <div class="col-md-3 column">
                                <div class="goods_container">
                                    <div><a href="/web/book/?b={{ item.id }}"><img alt="40x40" width="60" height="60" src="{{ item.picture.url }}" class="goods_img"/></a></div>
                                    <div style="text-align:left">
                                        <span class="goods_price">¥{{ item.price }}</span>
                                        <span class="goods_title"><a href="/web/book/?b={{ item.id }}">{{ item.bookname }}</a></span>
                                        <span class="goods_pos">{{ item.get_way_display }}</span>

                                    </div>
                                </div>
                            </div>
                            {% endfor %}



                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="evaluation">
                    <div class="container" style="margin-top:40px;font-size:15px;">
                        {%  for i in order_s %}
                        <!-- 一条评论开始 -->
                        <div class="row clearfix">
                            <div class="col-md-1 column">
                                <img src="/static/img/media/{{ i.buyer_image}}" width="72" height="72" class="little_head">
                            </div>
                            <div class="col-md-2 column">
                                <span>{% if i.anonymous  %}匿名用户{% else %}{{ i.buyer_name }} {% endif %}</span>
                            </div>
                            <div class="col-md-5 column">
                                <p>{{ i.comment }}</p>
                                <p class="date">{{ i.c_time }}</p>
                            </div>
                            <div class="col-md-1 column">
                                <span>评分：{{ i.score }}</span>
                            </div>
                            <div class="col-md-3 column">
                                <span>来自华南理工大学的买家</span>
                            </div>
                        </div>
                        {% endfor %}
                    {%  for i in order_b %}
                        <!-- 一条评论开始 -->
                        <div class="row clearfix">
                            <div class="col-md-1 column">
                                <img src="/static/img/media/{{ i.seller_image}}"width="72" height="72" class="little_head">
                            </div>
                            <div class="col-md-2 column">
                                <span>{% if i.anonymous  %}匿名用户{% else %}{{ i.seller_name }} {% endif %}</span>
                            </div>
                            <div class="col-md-5 column">
                                <p>{{ i.tobuyer_comment }}</p>
                                <p class="date">{{ i.tobuyer_c_time }}</p>
                            </div>
                            <div class="col-md-1 column">
                                <span>评分：{{ i.tobuyer_score }}</span>
                            </div>
                            <div class="col-md-3 column">
                                <span>来自华南理工大学的卖家</span>
                            </div>
                        </div>
                        {% endfor %}
                        <!-- 一条评论结束 -->
                        <hr/>


                        <hr/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

web/templates/own_book.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>易书</title>
    <!-- 包含头部信息用于适应不同设备 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 包含 bootstrap 样式表 -->
    <link rel="stylesheet" href="https://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href="/static/css/head.css" rel="stylesheet" type="text/css"/>
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript">
    function if_buy(){
        var t=confirm("你确定要拍下这件商品吗？")
        if(t==true){
            return "/web/buyer_center"
        }
        else {
            return "#"
        }
    }
    </script>
</head>
<body>
    <div id="white" style="opacity:0.9;"></div>

    <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid"> 
    <div class="navbar-header">
        <a class="navbar-brand" href="/web/home">首页</a>
    </div>
    <div>
        <ul class="nav navbar-nav">

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {{ user }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/PCenter">个人中心</a></li>
                    <li><a href="/web/login">退出登录</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    买家中心 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/buyer_center/?b=-1">已买到的宝贝</a></li>
                    <li><a href="/web/favorites">收藏夹</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    卖家中心 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/web/upload">发布新的二手课本</a></li>
                    <li><a href="/web/selling">已上架的课本</a></li>
                    <li><a href="/web/seller_center">已卖出的课本</a></li>
                </ul>
            </li>

        </ul>
    </div>
    </div>
</nav>


<div class="container" style="text-align:left;margin-top:40px;">
    {% for item in book  %}
    <div class="row clearfix">
        <div class="col-md-1 column"></div>
        <div class="col-md-3 column">
            <div style="border:#a4a4a4 1.5pt solid;padding:10px;">
                <img id="bid_pic" src="{{item.picture.url}}" style="width:100%">
            </div>
            <div style="margin-top:15px;"><span style="top:4px;"></span></div>
        </div>
        <div class="col-md-6 column">
            <div style="font-size:30px;"><b><span id="bid_title">{{ item.bookname }}</span></b></div>
            <div style="font-size:20px;margin-top:15px;"><span>价&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;格：￥</span><span style="font-size:25px;color:#68493a" id="bid_price">{{ item.price }}</span></div>
            <div style="font-size:20px;">配送方式：{{ item.get_way_display }}</div>
            <div style="margin-top:20px;">作者：{{ item.author }}</div>
            <div>出版社：{{ item.publisher }}</div>
            <div style="margin-top:20px;"><b>商品介绍</b></div>
            <div>{{ item.description }}</div>
            <div style="text-align:right;margin-top:10px;"><button type="button" style="display:none" onclick="location.href=if_buy()">立即购买</button></div>
        </div>
        <div class="col-md-2 column" style="text-align:center;">
            <div style="font-size:10px;">卖家：{{ item.seller.nickname }} </div>
            <img id="gid_pic" src="{{ item.seller.image.url}}" style="width:50%;margin:15px 0;">
            <div style="font-size:10px;">华南理工大学 南校</div>
        </div>
    </div>
    {% endfor %}
</div>

</body>
</html>

web/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册成功</title>
</head>
<body>
注册成功！
<p>正在跳转登录界面。。。如长时间无响应请点击：</p>
<p><a href="/web/login">链接</a></p>
<META HTTP-EQUIV="Refresh" CONTENT="1; URL=/web/login">
</body>
</html>

web/templates/success_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论成功</title>
</head>
<body>
评论成功！
<p>正在跳转至买家中心界面。。。如长时间无响应请点击：</p>
<p><a href="/web/buyer_center/?b=-1">链接</a></p>
<META HTTP-EQUIV="Refresh" CONTENT="1; URL=/web/buyer_center/?b=-1">
</body>
</html>

web/templates/success_return.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>退货成功</title>
</head>
<body>
退货成功！
<p>正在跳转至买家中心。。。如长时间无响应请点击：</p>
<p><a href="/web/buyer_center/?b=-1">链接</a></p>
<META HTTP-EQUIV="Refresh" CONTENT="1; URL=/web/buyer_center/?b=-1">
</body>
</html>